version: "3.9"
services:
  cp-control:
    container_name: cp-control
    build: ./cp-control
    ports:
      - 3000:80
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local