version: "3.4"
services:
  cp-proxy:
    container_name: cp-proxy
    restart: always
    build: ./cp-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - ENABLE_HTTPS=false
  cp-control:
    container_name: cp-control
    restart: always
    build: ./cp-control
  cp-db:
    container_name: cp-db
    restart: always
    build: ./cp-db
  cp-analyzer:
    container_name: cp-analyzer
    restart: always
    build: ./cp-analyzer
  cp-postgres:
    container_name: cp-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pdb&3Xif
    volumes:
      - db:/var/lib/postgresql/data
 
volumes:
  db:
    driver: local
