version: "3.4"
services:
  cp-control:
    container_name: cp-control
    restart: always
    build: ./cp-control
    ports:
      - 80:80
      - 443:443
    environment:
      - ENABLE_HTTPS=false
  cp-gateway:
    container_name: cp-gateway
    restart: always
    build: ./cp-gateway
    ports:
      - 5001:5001
  cp-db:
    container_name: cp-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pdb&3Xif
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  cp-routing:
    container_name: cp-routing
    ports:
      - "5002:8080"
    image: openrouteservice/openrouteservice:latest
    user: "${UID:-0}:${GID:-0}"
    #build:
    #context: ./cp-routing/openrouteservice/
    #args:
    #ORS_CONFIG: ./ors-api/src/main/resources/ors-config-sample.json
    #OSM_FILE: ./data/maps/germany-latest.osm.pbf
    volumes:
      - ./cp-routing/data/graphs:/home/ors/ors-core/data/graphs
      - ./cp-routing/data/elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./cp-routing/data/logs/ors:/home/ors/ors-core/logs/ors
      - ./cp-routing/data/logs/tomcat:/home/ors/tomcat/logs
      - ./cp-routing/data/conf:/home/ors/ors-conf
      - ./cp-routing/data/maps/germany-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
volumes:
  db:
    driver: local
