version: "3.4"
services:
  cp-gateway:
    container_name: cp-gateway
    restart: always
    build: ./cp-gateway
    ports:
      - '443:5001'
  cp-control:
    container_name: cp-control
    restart: always
    build: ./cp-control
    ports:
      - '80:80'
  cp-db:
    container_name: cp-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pdb&3Xif
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local