@startuml

skinparam linetype polyline
skinparam linetype ortho

node "Docker Compose ZDM Server" {
    
    component [           CP-Proxy           ] as proxy <<Node.js>>
    component [CP-Control] as control <<React>>
    

    component [CP-Routing] as routing <<Openrouteservice>>
    component [CP-Analyzer] as analyzer <<Python App>>
    component [CP-DB] as db <<Node.js>>
    database "SQL Database" {
        component [Postgres Instance] as postgres <<Postgres>>
    }

    note right of db
        Database abstraction via API
    end note

    note right of analyzer
        Data aggregation
        Pattern analysis
        Cluster analysis
    end note

    note left of proxy
        Internet-facing gateway
    end note
}

component [CP-Uploader] as uploader <<Python App>>

interface "Freight Market" as market
interface "File (.csv, .geojson, .xslx)" as file
interface "API" as api


proxy <-> control
uploader --> proxy
proxy <--> routing
proxy ---> analyzer
proxy <--> db
analyzer <--> db
db <--> postgres
market <--> analyzer
file --> uploader
api --> proxy

note left of uploader
    File input handling and uploading
    from local machines.
end note


note right of control
    Frontend dashboard
end note


@enduml
